#database
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3307/g7-re?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
        username: root
        password: 123456


# mybatis config
mybatis:
    type-aliases-package: com.g7.entity
    mapper-locations: classpath:mappers/*.xml
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# mybatis mapper config
mapper:
    mappers: com.g7.my.mapper.MyMapper
    not-empty: false
    identity: MYSQL
