server:
    port: 8080
    tomcat:
        uri-encoding: UTF-8
    max-http-header-size: 80KB

#database
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://49.51.97.143:3306/g7-re?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
        username: root
        password: g7re123


# mybatis config
mybatis:
    type-aliases-package: com.g7.entity
    mapper-locations: classpath:mappers/*.xml
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# mybatis mapper config
mapper:
    mappers: com.g7.my.mapper.MyMapper
    not-empty: false
    identity: MYSQL